webapp/chess/urls.py
from django.urls import path

from . import views

app_name = 'chess'
urlpatterns = [
	path('', views.index, name='index'),
]

webapp/neuralauth/urls.py
from django.urls import path

from . import views

app_name = 'neuralauth'
urlpatterns = [
	path('recognize/', views.recognize, name='recognize'),
	path('reset/', views.reset, name='reset'),
	path('compare/', views.compare, name='compare'),
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('chess/', include('chess.urls'), name='chess'),
    path('neuralauth/', include('neuralauth.urls'), name='neuralauth'),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    # This is needed so that hardcoded urls to static files can work
] + static('/', document_root=settings.STATIC_ROOT)

webapp/chess/models.py
from django.db import models

# Create your models here.

webapp/neuralauth/models.py
from django.db import models

# Create your models here.

webapp/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

webapp/chess/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def index(request):
	return render(request, 'chess/index.html', {})

webapp/neuralauth/views.py
import itertools
import os
import pickle
from collections import OrderedDict

import Pyro4
import matplotlib
import numpy as np
from django.http import HttpResponse
from rest_framework.authentication import SessionAuthentication, \
    BasicAuthentication
from rest_framework.decorators import api_view
from rest_framework.decorators import authentication_classes
from rest_framework.decorators import parser_classes
from rest_framework.decorators import permission_classes
from rest_framework.parsers import JSONParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from sklearn.metrics.pairwise import cosine_similarity

# in theory prevents matplotlib from wanting an x server to render things which will
# raise a tkinter exception if executed on a server
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas


def timestamps_to_dts(timestamps):
    """ Converts a list of timestamps to time deltas """
    orig = timestamps[0]
    timestamps = [i - orig for i in timestamps]
    timestamps[1:] = [timestamps[idx + 1] - timestamps[idx] for idx, i in
                      enumerate(timestamps[1:])]
    return timestamps


def translate(data):
    """
    Convert browser input data to the format that the neural network used
    while training:
    (timestamp, e.buttons, type, x, y)
    We'll also convert the timestamp to time differences and
    from milliseconds to seconds
    """

    result = []
    data = np.array(data, dtype=object)
    dts = timestamps_to_dts(data[:, 0])  # convert to time deltas
    dts = [i / 1000.0 for i in dts]  # convert to seconds
    data[:, 0] = dts

    buttons_map = {0: 'NoButton', 1: 'Left', 2: 'Right'}
    states_map = {0: 'Move', 1: 'Pressed', 2: 'Released', 3: 'Drag'}

    data[:, 1] = [buttons_map.get(i, 'Unknown') for i in data[:, 1]]
    data[:, 2] = [states_map.get(i, 'Unknown') for i in data[:, 2]]

    return data.tolist()


# Use pickle as an improvised database
def persist(id, obj):
    with open('state/user_{}_state.pkl'.format(id), 'w+b') as tmp:
        pickle.dump(obj, tmp)


def load(id):
    with open('state/user_{}_state.pkl'.format(id), 'rb') as tmp:
        return pickle.load(tmp)


def reset_state(id):
    with open('state/user_{}_state.pkl'.format(id), 'w+b') as tmp:
        pickle.dump(OrderedDict(), tmp)


def get_or_create_state(id):
    state = OrderedDict()

    try:
        state = load(id)
    except Exception:
        pass

    return state


def plot_confusion_matrix(cm, classes, range_min,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    plt.imshow(cm, interpolation='nearest', cmap=cmap, vmin=range_min, vmax=1.0)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

    thresh = 0.8
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, "{:.5f}".format(cm[i, j]),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('Users')
    plt.xlabel('Users')


@api_view(['GET'])
@authentication_classes((SessionAuthentication, BasicAuthentication))
@permission_classes((IsAuthenticated,))
@parser_classes((JSONParser,))
def compare(request):
    """ Returns a PNG image with a confusion matrix graph that shows how the
    network compares any user against every other user """

    if request.method == 'GET':

        rangemin = float(request.query_params['rangemin'])

        state = get_or_create_state(request.user.id)

        confusion_matrix = np.zeros((len(state.items()), len(state.items())))
        # this can be done with itertools but it uses lexicographic order?
        combinations = [(x, y) for x in enumerate(state.items()) for y in
                        enumerate(state.items())]
        for (i, (user1, embedding1)), (j, (user2, embedding2)) in combinations:
            confusion_matrix[i, j] = cosine_similarity(embedding1, embedding2)

        fig = plt.figure()
        plot_confusion_matrix(confusion_matrix, state.keys(), rangemin)
        canvas = FigureCanvas(fig)

        response = HttpResponse(content_type='image/png')
        canvas.print_png(response)
        return response


@api_view(['POST'])
@authentication_classes((SessionAuthentication, BasicAuthentication))
@permission_classes((IsAuthenticated,))
@parser_classes((JSONParser,))
def reset(request):
    """ Resets the saved recognition signatures"""
    if request.method == 'POST':
        reset_state(request.user.id)
        return Response()


@api_view(['POST'])
@authentication_classes((SessionAuthentication, BasicAuthentication))
@permission_classes((IsAuthenticated,))
@parser_classes((JSONParser,))
def recognize(request):
    """
    Sends the recorded input sequence the neural network which computes a 
    signature. The signature is saved and associated with the given user.
    """
    if request.method == 'POST':
        state = get_or_create_state(request.user.id)

        user = request.data['user']
        data = translate(request.data['input'])

        detector = Pyro4.Proxy('PYRONAME:neuralauth.detector')
        embedding = np.array(detector.prepare_and_predict(data, 1024, 768))

        # We assume the average embedding will be representative of all the
        # recorded sequences
        try:
            state[user] = np.mean([state[user], embedding], axis=0)
        except KeyError:
            state[user] = embedding

        persist(request.user.id, state)

        return Response(state[user])

webapp/polls/views.py
from django.shortcuts import render

# Create your views here.

webapp/webapp/views.py
from django.shortcuts import render


def index(request):
	return render(request, 'index.html', {})

webapp/chess/templates/chess/index.html
{% extends "base_generic.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'chess/css/chessboard-0.3.0.min.css' %}" />
<style type="text/css">

/* center text in progress bar */
.progress {
    position: relative;
}

.progress span {
    position: absolute;
    display: block;
    width: 100%;
    color: black;
}

/* supress bootstrap progress bar transitions */
.progress-bar {
    -webkit-transition: none !important;
    transition: none !important;
}
</style>
{% endblock %}


{% block content %}
<div class="row">
    <div class="col-xs-12">
        <h1>Chess</h1>
        <p>This is a small chess game. By playing it you can generate
        realistic mouse inputs and send them to the model. The model will
            then generate embeddings for each new input sequence and you
            will be able to see the distance between the different embeddings
            by looking at the confusion matrix chart below.</p>
        <p> To analyze some mouse input sequence write a unique name
            on the User field and then press the <b>RECORD USER</b> button. Now you
            can start playing the game or generating some specific mouse patterns.</p>
        <p>The data will be periodically sent to the model and an embedding or
        representation will be generated out of the sequence of inputs.
            If you keep producing input new embeddings will be generated and
            averaged with the previous ones.
        </p>
        <p> After some time press <b>STOP RECORDING</b>, write a different user
            name and then press <b>RECORD USER</b> Again. The confusion matrix chart
        will start showing the distance between every embedding generated
        for every different user. Ideally the distances should be bigger
        beetween very different users and smaller between more similar ones.<p>
        <p> If you want to reset everything press the <b>RESET STATE</b> button</p>
        <p> You can also adjust the color scale of the chart and press <b>REFRESH GRAPH</b> button to reload it.</p>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div id="board" ></div>
    </div>
    <div class="col-sm-6">
        <div class="well bs-component">
            <form class="form-horizontal" id="control-form">
                <fieldset>
                    <legend>Input analysis</legend>
                    <p>Type the id of an existing or a new user and press the 'record user' button to begin.</p>
                    <div class="form-group" id="form-group-inputUser">
                        <label for="inputUser" class="col-lg-4 control-label">User:</label>
                        <div class="col-lg-4">
                            <input class="form-control" id="inputUser" placeholder="username" type="text">
                        </div>
                        <div class="col-lg-4">
                            <button type="submit" id="record-user-btn" class="btn btn-primary">Record user</button>
                            <button type="submit" id="stop-record-btn" class="btn btn-primary" style="display: none">Stop recording</button>
                        </div>
                    </div>
                    <div class="form-group" id="form-group-minvalue">
                        <label for="inputMin" class="col-lg-4 control-label">Minimum color scale:</label>
                        <div class="col-lg-8">
                            <input class="form-control" id="inputMin" value="0.5" placeholder="0.5" type="text">
                        </div>
                    </div>
                </fieldset>
            </form>
            <div class="progress" style="display:none" id="progress-bar-container">
                <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;" id="progress-bar">
                    <span class="show">Recording user <span id="user-recording-alert-iduser"></span> input</span>
                </div>
            </div>
            <p>This <strong>Confusion Matrix</strong> shows the similarity of every user with respect to every other user as computed by the neural network:</p>
            <img class="img-responsive" src="/neuralauth/compare/?rangemin=0.0" id="graph-confusion-matrix">
            <br/>
            <p>Press this button to reset the data collected by the network</p>
            <button type="submit" id="btn-reset-state" class="btn btn-primary">Reset state</button>
            <button type="submit" id="btn-reload-graph" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span>&nbsp;&nbsp;refresh graph</button>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'neuralauth/neuralauth.js' %}"></script>
<script type="text/javascript">

// reload the confusion matrix on every sent batch
neuralauth.setOnRecognizeCb(function() {
    if(validate()) {
        d = new Date();
        min = parseFloat($("#inputMin").val());
        $("#graph-confusion-matrix").attr("src", "/neuralauth/compare/?rangemin="+min+"&touch="+d.getTime());
    }
});

// update the progress bar when input is recorded
neuralauth.setInputRecordCb(function(size) {
    var pct = (size / neuralauth.EVENT_BUFFER_SIZE) * 100;
    setTimeout(function() {
        $('#progress-bar').css('width', pct + '%');
    });
});

/* Validate the form */
function validate() {

    var valid = true;

    if($('#inputUser').val() == "") {
        $('#form-group-inputUser').addClass('has-error');        
        valid = false;
    } else {
        $('#form-group-inputUser').removeClass('has-error');
    }

    var inputMin = $('#inputMin').val();
    if(parseFloat(inputMin) == NaN || parseFloat(inputMin) < 0.0  || parseFloat(inputMin) > 10.0) {
        $('#form-group-minvalue').addClass('has-error');
        valid = false;
    } else {
        $('#form-group-minvalue').removeClass('has-error');
    }

    return valid;
}

// prevent form from submitting
$("#control-form").submit(function(e) {
    e.preventDefault();
});

$('#record-user-btn').click(function() {
    if(validate()) {
        $('#progress-bar-container').show();
        $('#record-user-btn').hide()
        $('#stop-record-btn').show();

        neuralauth.start($('#inputUser').val())
    }
});

$('#stop-record-btn').click(function() {
    $('#progress-bar-container').hide();
    $('#stop-record-btn').hide();
    $("#record-user-btn").show();
    $("#user-recording-alert").hide();
    $('#progress-bar').css('width', 0 + '%');
    neuralauth.stop();
});

$('#btn-reset-state').click(function() {
    if(validate()) {
        neuralauth.reset();
        d = new Date();
        min = parseFloat($("#inputMin").val());
        $("#graph-confusion-matrix").attr("src", "/neuralauth/compare/?rangemin="+min+"&touch="+d.getTime());
    }
});

$('#btn-reload-graph').click(function() {

    var valid = true;
    var inputMin = $('#inputMin').val();
    if(parseFloat(inputMin) == NaN || parseFloat(inputMin) < 0.0  || parseFloat(inputMin) > 10.0) {
        $('#form-group-minvalue').addClass('has-error');
        valid = false;
    } else {
        $('#form-group-minvalue').removeClass('has-error');
    }


    if(valid) {
        d = new Date();
        min = parseFloat($("#inputMin").val());
        $("#graph-confusion-matrix").attr("src", "/neuralauth/compare/?rangemin="+min+"&touch="+d.getTime());
    }
});

</script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/chess.js/0.10.2/chess.js"></script>
<script src="{% static 'chess/js/chessboard-0.3.0.min.js' %}"></script>
<script type="text/javascript">

// Adjust board size 
//wwidth = $(window).width()
//wheight = $(window).height() - 200;
//$('#board').width(wheight);

var board,
    game = new Chess();

// do not pick up pieces if the game is over
// only pick up pieces for White
var onDragStart = function(source, piece, position, orientation) {
    if (game.in_checkmate() === true || game.in_draw() === true ||
            piece.search(/^b/) !== -1) {
        return false;
    }
};

var makeRandomMove = function() {
    var possibleMoves = game.moves();

    // game over
    if (possibleMoves.length === 0) return;

    var randomIndex = Math.floor(Math.random() * possibleMoves.length);
    game.move(possibleMoves[randomIndex]);
    board.position(game.fen());
};

var onDrop = function(source, target) {
    // see if the move is legal
    var move = game.move({
        from: source,
        to: target,
        promotion: 'q' // NOTE: always promote to a queen for example simplicity
    });

    // illegal move
    if (move === null) return 'snapback';

    // make random legal move for black
    window.setTimeout(makeRandomMove, 250);
};

// update the board position after the piece snap
// for castling, en passant, pawn promotion
var onSnapEnd = function() {
    board.position(game.fen());
};

var cfg = {
    draggable: true,
    position: 'start',
    onDragStart: onDragStart,
    onDrop: onDrop,
    onSnapEnd: onSnapEnd
};
board = ChessBoard('board', cfg);


</script>
{% endblock %}

webapp/templates/base_generic.html
{% load static %} 
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>

    {% block head %}
    {% endblock %}
</head>

<body>
<!--[if lt IE 8]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand">DEMO </a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
{% url 'index' as url %}
          <li {% if request.path == url %} class="active"{% endif %}><a href="{{ url }}">Home</a></li>

<!-- {% url 'polls:index' as url %}          
          <li {% if request.path == url %} class="active"{% endif %}><a href="{{ url }}">Polls</a></li> -->


<!--{% if request.user.is_authenticated %}
	{% url 'deep:index' as url %}
          <li {% if request.path == url %} class="active"{% endif %}><a href="{{ url }}">C&C</a></li>
{% endif %}
-->

{% if request.user.is_authenticated %}
	{% url 'chess:index' as url %}
			<li {% if request.path == url %} class="active"{% endif %}><a href="{{ url }}">Chess</a></li>
{% endif %}

{% if request.user.is_superuser %}
	{% url 'admin:index' as url %}
          <li {% if request.path == url %} class="active"{% endif %}><a href="{{ url }}">Admin</a></li>
{% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
          <!--<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>-->
{% if user.is_authenticated %}
          <p class="navbar-text">User: {{ user.get_username }}</p>
          <li><a href="{% url 'logout'%}?next={% url 'index'%}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
{% else %}
          <li><a href="{% url 'login'%}?next={{request.path}}"><span class="glyphicon glyphicon-log-out"></span> Login</a></li>
{% endif %}
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container" class="col-sm-12 " style="margin-top:90px">
{% block content %}
{% endblock %}

  <hr/>

  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Made by <a href="" rel="nofollow">Manuel Martín</a>. Contact at <a href="mailto:manuel.martinm@pm.me">manuel.martinm@pm.me</a>.</p>
      </div>
    </div>
  </footer>

  </div>
      
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.2.min.js'%}"><\/script>')</script>
  <script src="{% static 'js/vendor/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/main.js'%}"></script>

  {% block scripts %}
  {% endblock %}
</body>
</html>